-- MySQL Script generated by MySQL Workbench
-- 11/03/15 16:46:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema txstexe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema txstexe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `txstexe` DEFAULT CHARACTER SET utf8 ;
USE `txstexe` ;

-- -----------------------------------------------------
-- Table `txstexe`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Club` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Club` (
  `club_name` VARCHAR(20) NOT NULL,
  `contact_email` VARCHAR(20) NULL,
  `building` VARCHAR(20) NULL,
  `room` VARCHAR(10) NULL,
  PRIMARY KEY (`club_name`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Member` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Member` (
  `member_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `fname` VARCHAR(25) NULL,
  `mi` VARCHAR(1) NULL,
  `lname` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  `major` VARCHAR(25) NULL,
  `class` VARCHAR(10) NULL,
  `grad_date` DATE NULL,
  `tshirt_size` VARCHAR(5) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`member_id`) ,
  INDEX `club_name_idx` (`club_name` ASC) ,
  CONSTRAINT `club_name`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Officer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Officer` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Officer` (
  `officer_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `member_id` BIGINT(20) NULL,
  `date_elected` DATE NULL,
  PRIMARY KEY (`officer_id`) ,
  INDEX `club_name_idx` (`club_name` ASC) ,
  INDEX `member_id_idx` (`member_id` ASC) ,
  CONSTRAINT `club_name_officer`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_officer`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Donor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Donor` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Donor` (
  `donor_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `donation_id` BIGINT(20) NULL,
  `fname` VARCHAR(25) NULL,
  `mi` VARCHAR(1) NULL,
  `lname` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`donor_id`) ,
  INDEX `donation_id_idx` (`donation_id` ASC) ,
  CONSTRAINT `donation_id_fk`
    FOREIGN KEY (`donation_id`)
    REFERENCES `txstexe`.`Donation` (`donation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Donation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Donation` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Donation` (
  `donation_id` BIGINT(20) NOT NULL,
  `donor_id` BIGINT(20) NULL,
  `amount` DECIMAL(10,2) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`donation_id`) ,
  INDEX `donor_id_idx` (`donor_id` ASC) ,
  CONSTRAINT `donor_id`
    FOREIGN KEY (`donor_id`)
    REFERENCES `txstexe`.`Donor` (`donor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Blog` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Blog` (
  `blog` VARCHAR(20) NOT NULL,
  `club_name` VARCHAR(20) NULL,
  `officer_id` BIGINT(20) NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`blog`) ,
  INDEX `officer_id_idx` (`officer_id` ASC) ,
  UNIQUE INDEX `club_name_UNIQUE` (`club_name` ASC) ,
  CONSTRAINT `officer_id`
    FOREIGN KEY (`officer_id`)
    REFERENCES `txstexe`.`Officer` (`officer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `club_name_blog`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Officer` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`MailingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`MailingList` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`MailingList` (
  `mail_list_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `member_id` BIGINT(20) NULL,
  `mail_list_name` VARCHAR(25) NULL,
  PRIMARY KEY (`mail_list_id`) ,
  INDEX `member_id_idx` (`member_id` ASC) ,
  INDEX `club_name_idx` (`club_name` ASC) ,
  CONSTRAINT `club_name_ml`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_ml`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Event` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Event` (
  `event_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `event_name` VARCHAR(50) NULL,
  `event_type` VARCHAR(50) NULL,
  `building` VARCHAR(25) NULL,
  `room` VARCHAR(10) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`event_id`) ,
  INDEX `club_name_idx` (`club_name` ASC) ,
  CONSTRAINT `club_name_oncampusevent`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Credential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Credential` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Credential` (
  `credential_id` BIGINT(20) NOT NULL,
  `member_id` BIGINT(20) NULL,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  PRIMARY KEY (`credential_id`) ,
  CONSTRAINT `member`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Signup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Signup` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Signup` (
  `signup_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `event_id` BIGINT(20) NULL,
  `member_id` BIGINT(20) NULL,
  `points` BIGINT(20) NULL,
  PRIMARY KEY (`signup_id`) ,
  INDEX `oncampusevent_id_idx` (`event_id` ASC) ,
  INDEX `member_id_idx` (`member_id` ASC) ,
  CONSTRAINT `event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `txstexe`.`Event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_event`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`ProjectGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`ProjectGroup` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`ProjectGroup` (
  `proj_group_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `member_id` BIGINT(20) NULL,
  `proj_lead_id` BIGINT(20) NULL,
  `building` VARCHAR(25) NULL,
  `room` VARCHAR(10) NULL,
  `datetime` DATETIME NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`proj_group_id`) ,
  INDEX `club_name_idx` (`club_name` ASC) ,
  INDEX `member_id_idx` (`member_id` ASC) ,
  CONSTRAINT `club_name_projectgroup`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_projectgroup`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Forum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Forum` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Forum` (
  `forum_name` VARCHAR(25) NOT NULL,
  `club_name` VARCHAR(20) NULL,
  PRIMARY KEY (`forum_name`) ,
  INDEX `club_name_idx` (`club_name` ASC) ,
  CONSTRAINT `club_name_forum`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Topic` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Topic` (
  `topic_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `forum_name` VARCHAR(25) NULL,
  `topic` VARCHAR(50) NULL,
  `category` VARCHAR(50) NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`topic_id`) ,
  INDEX `forum_name_idx` (`forum_name` ASC) ,
  CONSTRAINT `forum_name`
    FOREIGN KEY (`forum_name`)
    REFERENCES `txstexe`.`Forum` (`forum_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Comment` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Comment` (
  `comment_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `topic_id` BIGINT(20) NULL,
  `member_id` BIGINT(20) NULL,
  `comment` MEDIUMTEXT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`comment_id`) ,
  INDEX `topic_id_idx` (`topic_id` ASC) ,
  INDEX `member_id_idx` (`member_id` ASC) ,
  CONSTRAINT `topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `txstexe`.`Topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_comment`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`News` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`News` (
  `news_item_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `news_item` MEDIUMTEXT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`news_item_id`) ,
  INDEX `club_name_idx` (`club_name` ASC) ,
  CONSTRAINT `club_name_news`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Points` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Points` (
  `points_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `member_id` BIGINT(20) NULL,
  `points_earned` BIGINT(20) NULL,
  PRIMARY KEY (`points_id`) ,
  INDEX `points_member_id_idx` (`member_id` ASC) ,
  CONSTRAINT `points_member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
