-- MySQL Script generated by MySQL Workbench
-- 10/30/15 12:23:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema txstexe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema txstexe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `txstexe` DEFAULT CHARACTER SET utf8 ;
USE `txstexe` ;

-- -----------------------------------------------------
-- Table `txstexe`.`Club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Club` (
  `club_name` VARCHAR(20) NOT NULL,
  `contact_id` BIGINT(20) NULL,
  `building` VARCHAR(20) NULL,
  `room` VARCHAR(10) NULL,
  PRIMARY KEY (`club_name`),
  INDEX `club_poc_idx` (`contact_id` ASC),
  CONSTRAINT `club_poc`
    FOREIGN KEY (`contact_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Member` (
  `member_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `fname` VARCHAR(25) NULL,
  `mi` VARCHAR(1) NULL,
  `lname` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  `major` VARCHAR(25) NULL,
  `class` VARCHAR(10) NULL,
  `grad_date` DATE NULL,
  `tshirt_size` VARCHAR(5) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`member_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Officer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Officer` (
  `officer_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `member_id` BIGINT(20) NULL,
  `date_elected` DATE NULL,
  PRIMARY KEY (`officer_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  INDEX `member_id_idx` (`member_id` ASC),
  CONSTRAINT `club_name_officer`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_officer`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Donation` (
  `donation_id` BIGINT(20) NOT NULL,
  `donor_id` BIGINT(20) NULL,
  `amount` DECIMAL(10,2) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`donation_id`),
  INDEX `donor_id_idx` (`donor_id` ASC),
  CONSTRAINT `donor_id`
    FOREIGN KEY (`donor_id`)
    REFERENCES `txstexe`.`Donor` (`donor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Donor` (
  `donor_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `donation_id` BIGINT(20) NULL,
  `fname` VARCHAR(20) NULL,
  `mi` VARCHAR(1) NULL,
  `lname` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`donor_id`),
  INDEX `donation_id_idx` (`donation_id` ASC),
  CONSTRAINT `donation_id`
    FOREIGN KEY (`donation_id`)
    REFERENCES `txstexe`.`Donation` (`donation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Blog` (
  `blog` VARCHAR(20) NOT NULL,
  `club_name` VARCHAR(20) NULL,
  `officer_id` BIGINT(20) NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`blog`),
  INDEX `officer_id_idx` (`officer_id` ASC),
  UNIQUE INDEX `club_name_UNIQUE` (`club_name` ASC),
  CONSTRAINT `officer_id`
    FOREIGN KEY (`officer_id`)
    REFERENCES `txstexe`.`Officer` (`officer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `club_name_blog`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Officer` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Mailing List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Mailing List` (
  `mail_list_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `member_id` BIGINT(20) NULL,
  `mail_list_name` VARCHAR(25) NULL,
  PRIMARY KEY (`mail_list_id`),
  INDEX `member_id_idx` (`member_id` ASC),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_ml`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_ml`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`OnCampusEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`OnCampusEvent` (
  `oncampusevent_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `oncampusevent_name` VARCHAR(50) NULL,
  `oncampusevent_type` VARCHAR(50) NULL,
  `building` VARCHAR(25) NULL,
  `room` VARCHAR(10) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`oncampusevent_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_oncampusevent`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Credential` (
  `credential_id` BIGINT(20) NOT NULL,
  `member_id` BIGINT(20) NULL,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  PRIMARY KEY (`credential_id`),
  UNIQUE INDEX `member_id_UNIQUE` (`member_id` ASC),
  CONSTRAINT `member`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`OnCampusEventSignup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`OnCampusEventSignup` (
  `oncampusevent_signup_id` BIGINT(20) NOT NULL,
  `oncampusevent_id` BIGINT(20) NULL,
  `member_id` BIGINT(2) NULL,
  PRIMARY KEY (`oncampusevent_signup_id`),
  INDEX `oncampusevent_id_idx` (`oncampusevent_id` ASC),
  INDEX `member_id_idx` (`member_id` ASC),
  CONSTRAINT `oncampusevent_id`
    FOREIGN KEY (`oncampusevent_id`)
    REFERENCES `txstexe`.`OnCampusEvent` (`oncampusevent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_oncampusevent`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Project Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Project Group` (
  `proj_group_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `member_id` BIGINT(20) NULL,
  `proj_lead_id` BIGINT(20) NULL,
  `building` VARCHAR(25) NULL,
  `room` VARCHAR(10) NULL,
  `datetime` DATETIME NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`proj_group_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  INDEX `member_id_idx` (`member_id` ASC),
  CONSTRAINT `club_name_projectgroup`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_projectgroup`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`OffCampusEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`OffCampusEvent` (
  `offcampusevent_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `offcampusevent_name` VARCHAR(50) NULL,
  `offcampusevent_type` VARCHAR(50) NULL,
  `address` VARCHAR(100) NULL,
  `city` VARCHAR(50) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`offcampusevent_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_offcampusevent`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`OffCampusEventSignup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`OffCampusEventSignup` (
  `offcampusevent_signup_id` BIGINT(20) NOT NULL,
  `offcampusevent_id` BIGINT(20) NULL,
  `member_id` BIGINT(2) NULL,
  PRIMARY KEY (`offcampusevent_signup_id`),
  INDEX `member_id_idx` (`member_id` ASC),
  INDEX `offcampusevent_id_idx` (`offcampusevent_id` ASC),
  CONSTRAINT `offcampusevent_id`
    FOREIGN KEY (`offcampusevent_id`)
    REFERENCES `txstexe`.`OffCampusEvent` (`offcampusevent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_offcampusevent`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Forum` (
  `forum_name` VARCHAR(25) NOT NULL,
  `club_name` VARCHAR(20) NULL,
  PRIMARY KEY (`forum_name`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_forum`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Topic` (
  `topic_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `forum_name` VARCHAR(25) NULL,
  `topic` VARCHAR(50) NULL,
  `category` VARCHAR(50) NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`topic_id`),
  INDEX `forum_name_idx` (`forum_name` ASC),
  CONSTRAINT `forum_name`
    FOREIGN KEY (`forum_name`)
    REFERENCES `txstexe`.`Forum` (`forum_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`Comment` (
  `comment_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `topic_id` BIGINT(20) NULL,
  `member_id` BIGINT(20) NULL,
  `comment` MEDIUMTEXT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `topic_id_idx` (`topic_id` ASC),
  INDEX `member_id_idx` (`member_id` ASC),
  CONSTRAINT `topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `txstexe`.`Topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_comment`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `txstexe`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `txstexe`.`News` (
  `news_item_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL,
  `news_item` MEDIUMTEXT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`news_item_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_news`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
