-- MySQL Script generated by MySQL Workbench
-- 07/02/16 13:59:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema txstexe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `txstexe` ;

-- -----------------------------------------------------
-- Schema txstexe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `txstexe` DEFAULT CHARACTER SET utf8 ;
USE `txstexe` ;

-- -----------------------------------------------------
-- Table `txstexe`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Club` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Club` (
  `club_name` VARCHAR(20) NOT NULL,
  `contact_email` VARCHAR(20) NULL DEFAULT NULL,
  `building` VARCHAR(20) NULL DEFAULT NULL,
  `room` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`club_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Member` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Member` (
  `member_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL DEFAULT NULL,
  `fname` VARCHAR(25) NULL DEFAULT NULL,
  `mi` VARCHAR(1) NULL DEFAULT NULL,
  `lname` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `email_hash` VARCHAR(100) NULL DEFAULT NULL,
  `major` VARCHAR(25) NULL DEFAULT NULL,
  `class` VARCHAR(10) NULL DEFAULT NULL,
  `grad_date` DATE NULL DEFAULT NULL,
  `tshirt_size` VARCHAR(6) NULL DEFAULT NULL,
  `paid` TINYINT(1) NULL DEFAULT '0',
  `post_count` BIGINT(20) NULL DEFAULT '0',
  `points` BIGINT(20) NULL DEFAULT '0',
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `facebook_id` VARCHAR(50) NULL DEFAULT NULL,
  `facebook_token` VARCHAR(50) NULL DEFAULT NULL,
  `subscribe` TINYINT(1) NULL DEFAULT '0',
  `privs` BIGINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`member_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Forum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Forum` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Forum` (
  `forum_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `forum_name` VARCHAR(25) NOT NULL,
  `club_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`forum_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_forum`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Topic` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Topic` (
  `topic_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `forum_id` BIGINT(20) NULL DEFAULT NULL,
  `topic_name` VARCHAR(45) NULL DEFAULT NULL,
  `topic_description` MEDIUMTEXT NULL DEFAULT NULL,
  `post_count` BIGINT(20) NULL DEFAULT '0',
  PRIMARY KEY (`topic_id`),
  INDEX `forum_name_idx` (`forum_id` ASC),
  CONSTRAINT `forum_id`
    FOREIGN KEY (`forum_id`)
    REFERENCES `txstexe`.`Forum` (`forum_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Thread` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Thread` (
  `thread_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `thread_name` VARCHAR(45) NULL DEFAULT NULL,
  `topic_id` BIGINT(20) NULL DEFAULT NULL,
  `thread_op_id` BIGINT(20) NULL DEFAULT NULL,
  `datetime` DATETIME NULL DEFAULT NULL,
  `post_count` BIGINT(20) NULL DEFAULT '0',
  PRIMARY KEY (`thread_id`),
  INDEX `topic_name_idx` (`topic_id` ASC),
  INDEX `op_idx` (`thread_op_id` ASC),
  CONSTRAINT `op`
    FOREIGN KEY (`thread_op_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `txstexe`.`Topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Comment` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Comment` (
  `comment_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `thread_id` BIGINT(20) NULL DEFAULT NULL,
  `member_id` BIGINT(20) NULL DEFAULT NULL,
  `comment` MEDIUMTEXT NULL DEFAULT NULL,
  `datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `member_id_idx` (`member_id` ASC),
  INDEX `thread_id_idx` (`thread_id` ASC),
  CONSTRAINT `member_id_comment`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `thread_id`
    FOREIGN KEY (`thread_id`)
    REFERENCES `txstexe`.`Thread` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Credential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Credential` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Credential` (
  `credential_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `member_id` BIGINT(20) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`credential_id`),
  INDEX `member` (`member_id` ASC),
  CONSTRAINT `member`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Donor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Donor` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Donor` (
  `donor_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(25) NULL DEFAULT NULL,
  `mi` VARCHAR(1) NULL DEFAULT NULL,
  `lname` VARCHAR(25) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`donor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Donation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Donation` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Donation` (
  `donation_id` BIGINT(20) NOT NULL,
  `donor_id` BIGINT(20) NULL DEFAULT NULL,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`donation_id`),
  INDEX `donor_id_idx` (`donor_id` ASC),
  CONSTRAINT `donor_id`
    FOREIGN KEY (`donor_id`)
    REFERENCES `txstexe`.`Donor` (`donor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`MailingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`MailingList` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`MailingList` (
  `mail_list_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL DEFAULT NULL,
  `member_id` BIGINT(20) NULL DEFAULT NULL,
  `mail_list_name` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`mail_list_id`),
  INDEX `member_id_idx` (`member_id` ASC),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_ml`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_ml`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`News` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`News` (
  `news_item_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL DEFAULT NULL,
  `news_item` MEDIUMTEXT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`news_item_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_news`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Officer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Officer` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Officer` (
  `officer_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL DEFAULT NULL,
  `member_id` BIGINT(20) NULL DEFAULT NULL,
  `date_elected` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`officer_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  INDEX `member_id_idx` (`member_id` ASC),
  CONSTRAINT `club_name_officer`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id_officer`
    FOREIGN KEY (`member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`ProjectGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`ProjectGroup` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`ProjectGroup` (
  `proj_group_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(20) NULL DEFAULT NULL,
  `proj_lead_id` BIGINT(20) NULL DEFAULT NULL,
  `building` VARCHAR(25) NULL DEFAULT NULL,
  `room` VARCHAR(10) NULL DEFAULT NULL,
  `datetime` DATETIME NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`proj_group_id`),
  INDEX `club_name_idx` (`club_name` ASC),
  CONSTRAINT `club_name_projectgroup`
    FOREIGN KEY (`club_name`)
    REFERENCES `txstexe`.`Club` (`club_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Event` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Event` (
  `event_id` VARCHAR(50) NOT NULL,
  `points` BIGINT(20) NULL,
  `event_id_remote` VARCHAR(45) NULL,
  INDEX `oncampusevent_id_idx` (`event_id` ASC),
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`ProjectGroup_has_Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`ProjectGroup_has_Member` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`ProjectGroup_has_Member` (
  `ProjectGroup_proj_group_id` BIGINT(20) NOT NULL,
  `Member_member_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ProjectGroup_proj_group_id`, `Member_member_id`),
  INDEX `fk_ProjectGroup_has_Member_Member1_idx` (`Member_member_id` ASC),
  INDEX `fk_ProjectGroup_has_Member_ProjectGroup1_idx` (`ProjectGroup_proj_group_id` ASC),
  CONSTRAINT `fk_ProjectGroup_has_Member_ProjectGroup1`
    FOREIGN KEY (`ProjectGroup_proj_group_id`)
    REFERENCES `txstexe`.`ProjectGroup` (`proj_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectGroup_has_Member_Member1`
    FOREIGN KEY (`Member_member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `txstexe`.`Member_has_Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `txstexe`.`Member_has_Event` ;

CREATE TABLE IF NOT EXISTS `txstexe`.`Member_has_Event` (
  `Member_member_id` BIGINT(20) NOT NULL,
  `Event_event_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Member_member_id`, `Event_event_id`),
  INDEX `fk_Member_has_Event1_Event1_idx` (`Event_event_id` ASC),
  INDEX `fk_Member_has_Event1_Member1_idx` (`Member_member_id` ASC),
  CONSTRAINT `fk_Member_has_Event1_Member1`
    FOREIGN KEY (`Member_member_id`)
    REFERENCES `txstexe`.`Member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_has_Event1_Event1`
    FOREIGN KEY (`Event_event_id`)
    REFERENCES `txstexe`.`Event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `txstexe`;

DELIMITER $$

USE `txstexe`$$
DROP TRIGGER IF EXISTS `txstexe`.`add_start_date` $$
USE `txstexe`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `txstexe`.`add_start_date`
BEFORE INSERT ON `txstexe`.`Member`
FOR EACH ROW
BEGIN
	set NEW.start_date = NOW();
END$$


USE `txstexe`$$
DROP TRIGGER IF EXISTS `txstexe`.`add_thread_date` $$
USE `txstexe`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `txstexe`.`add_thread_date`
BEFORE INSERT ON `txstexe`.`Thread`
FOR EACH ROW
BEGIN
	set NEW.datetime = NOW();
END$$


USE `txstexe`$$
DROP TRIGGER IF EXISTS `txstexe`.`add_post_date` $$
USE `txstexe`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `txstexe`.`add_post_date`
BEFORE INSERT ON `txstexe`.`Comment`
FOR EACH ROW
BEGIN
	set NEW.datetime = NOW();
END$$


USE `txstexe`$$
DROP TRIGGER IF EXISTS `txstexe`.`update_post_date` $$
USE `txstexe`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `txstexe`.`update_post_date`
BEFORE UPDATE ON `txstexe`.`Comment`
FOR EACH ROW
BEGIN
	set NEW.datetime = NOW();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
